name: Java Maven Build and Publish Artifact

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: target/*.jar

  docker_build_and_push:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev

      - name: Create Artifact Repository
        run: |
          gcloud artifacts repositories create my-repo --repository-format=docker --location=northamerica-northeast1 --project=ayush-424308

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package
          path: ./target

      - name: Build and push Docker image
        run: |
          docker build -t northamerica-northeast1-docker.pkg.dev/ayush-424308/my-repo/my-image:latest .
          docker push northamerica-northeast1-docker.pkg.dev/ayush-424308/my-repo/my-image:latest
