name: Java Maven Build, Publish, and Deploy

on:
  push:
    branches: ["uat3"]
  pull_request:
    branches: ["uat3"]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: target/*.jar

  docker_build_and_push:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to JFrog Artifactory
        run: echo "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }}" | docker login ${{ secrets.JFROG_URL }} --username ${{ secrets.JFROG_USERNAME }} --password-stdin

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package
          path: ./target

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.JFROG_URL }}/my-repo1/my-image:latest .
          docker push ${{ secrets.JFROG_URL }}/my-repo1/my-image:latest

  create_and_deploy_gke:
    needs: docker_build_and_push
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Add Google Cloud SDK distribution URI as a package source
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install -y apt-transport-https ca-certificates
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

      - name: Update package list and install google-cloud-sdk-gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Create GKE cluster
        run: |
          gcloud container clusters create my-gke-cluster --zone northamerica-northeast1-a --project ayush-424308 --machine-type=e2-medium --num-nodes=1 --disk-size=20 || echo "Cluster already exists"

      - name: Set up GKE credentials
        run: |
          gcloud container clusters get-credentials my-gke-cluster --zone northamerica-northeast1-a --project ayush-424308

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Delete existing deployment
        run: kubectl delete deployment my-deployment || echo "Deployment does not exist"

      - name: Apply Kubernetes Deployment
        run: kubectl apply -f deployment.yaml

      - name: Get details of crashing pods
        run: |
          kubectl get pods -o wide
          kubectl describe pod -l app=my-app

      - name: Get logs from crashing pods
        run: |
          kubectl logs -l app=my-app --all-containers=true --max-log-requests=10
          
      - name: Rollout status of deployment
        run: kubectl rollout status deployment/my-deployment --timeout=600s

  delete_resources:
    runs-on: ubuntu-latest
    needs: create_and_deploy_gke
    if: always()
    steps:
      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Delete GKE Cluster
        run: |
          gcloud container clusters delete my-gke-cluster --zone northamerica-northeast1-a --project ayush-424308 --quiet || echo "Cluster does not exist"

      - name: Delete Docker Image from JFrog
        run: |
          docker rmi ${{ secrets.JFROG_URL }}/my-repo1/my-image:latest || echo "Image does not exist"

      - name: Delete Pods in Kubernetes
        run: |
          kubectl delete pods -l app=my-app || echo "Pods do not exist"

      - name: Delete Deployment in Kubernetes
        run: |
          kubectl delete deployment my-deployment || echo "Deployment does not exist"

      - name: Clean up repository clone
        run: |
          rm -rf $GITHUB_WORKSPACE
