name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2

jobs:
  lint:
    runs-on: ubuntu-latest  # Use latest Ubuntu version for better support
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v2  # Use version 2 to avoid deprecated commands
      with:
        python-version: '3.x'  # Specify the Python version you need
    - name: list of files for debugging
      run: ls -alh
    - name: Install requirements
      run: pip install --quiet --requirement .github/workflows/requirements.txt
    - name: Lint code
      run: |
        echo "Running flake8 linting..."
        flake8 --ignore=E501,E231 .github/workflows/*.py
        echo "Running pylint linting.........."
        pylint --disable=C0301 --disable=C0326 .github/workflows/*.py
    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p ".github/workflows/*.py"
